### ISSUE TITLE
Fix footer logo in dark theme

### ISSUE THREAD

**Issue by AngeloCG97** [eoscostarica/guide.eoscostarica.io#220]
![Captura de pantalla (435)](https://user-images.githubusercontent.com/51149817/104484319-c6906180-558e-11eb-80e8-8915436ed858.png)

**Comment by leisterfrancisco** [comment]
@xavier506, @AngeloCG97  According to the documentation, there is no attribute to set a dark footer logo mode, more information about this, [could be found here](https://github.com/facebook/docusaurus/issues/3989), in summary, someone made the change but it seems to not be published yet, because I tried to locally update the a newer Docusaurus version but it is still not working, so what would you recommend to me to do with this? try to edit manually?

**Comment by AngeloCG97** [comment]
Good @leisterfrancisco an option is change manual  logo when is active the dark theme
