### ISSUE TITLE
Update Developer Tools Docs

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#262]
After our session with @tetogomez on the Tech stack we will be working with lets update our favorite tools section

https://guide.eoscostarica.io/docs/developer-tools

- [x] Apollo 
- [x] Axios
- [x] PropTypes
- [x] Hapi

**Comment by Edgar097** [comment]
@steph222 this is the information for first 3 tools
***
## EOSIO

### What is EOSIO?

EOSIO is open-source software that enables launching highly configurable blockchain networks on which developers and entrepreneurs can run highly performant blockchain applications. For more depth information about EOSIO visit [Learn EOS](https://guide.eoscostarica.io/docs/eos-learn/eosio-protocol).

### Why we use EOSIO?

Here are some reasons why we use EOSIO:

1. **It's scalable**. For businesses that need to transact with thousands of customers simultaneously, for example, this transaction speed is insufficient. EOSIO, on the other hand, has been benchmarked to process over 4,000 transactions per second on its public blockchain, which means that it is 200 times faster than its closest competitor and that’s just the public network.  

2. **It’s fast**.  By using EOSIO apps, consumers and enterprises do not even need to know that they’re using a ‘blockchain app’; all they know is that whatever data they have inputted for any transaction is more secure but no slower than your normal, non-blockchain app.  

3. **It’s virtually free**. Unlike other blockchain protocols, EOSIO offers a more favorable cost model for consumers and developers, as it eliminates the need for transaction fees.  

4. **It’s green**. One of the most common complaints you hear about blockchain technology is just how expensive and environmentally-unfriendly it is. Indeed, a lot of blockchain platforms require a substantial amount of electricity to run the computers needed to manage the distributed database.

>[More information](https://block.one/news/four-reasons-why-developers-and-enterprises-are-looking-at-the-eosio-blockchain-protocol/#:~:text=Unlike%20other%20blockchain%20protocols%2C%20EOSIO,apps%20are%20free%20to%20use.)

### Instalation of EOSIO

We have a guide for you to start in the EOSIO world visit.

* * *

## jq

### What is jq?

A lightweight and flexible command-line JSON processor. jq is like [sed](https://www.geeksforgeeks.org/sed-command-in-linux-unix-with-examples/) for JSON data you can use it to slice and filter and map and transform structured data with the same ease that sed, awk, grep and friends let you play with text.

### Why we use jq?

<figure
class="video_container">
    <iframe width="100%"
    height="315" src="https://www.youtube.com/embed/EvpwhGeiH0U" frameborder="0" allowfullscreen="true">
    </iframe>
</figure>

>[Tutorial](https://stedolan.github.io/jq/tutorial/)

### Instalation of jq

Intall jq from the [jq page](https://stedolan.github.io/jq/).

**Follow this video if you are using Windows OS**
<figure
class="video_container">
    <iframe width="100%"
    height="315" src="https://www.youtube.com/embed/rrjIVepRqPI" frameborder="0" allowfullscreen="true">
    </iframe>
</figure>

[Click here](https://jqplay.org/) if you want a place to try jq. The jq [GitHub](https://github.com/stedolan/jq) for more information.

* * *

## React JS

### What is React JS?

React is an open-source JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications.

### Why we use React JS?

1. **Fast Learning Curve**. React is very a simple and lightweight library that only deals with the view layer.
2. **Reusable Components**. React provides a component based structure. Components are your lego pieces. You start with tiny components like button, checkbox, dropdown etc. and the you create wrapper components composed of those smaller components.
3. **Fast render with Virtual DOM**. Updating DOM is usually the bottleneck when it comes to the web performance. React is trying to solve this problem by using something called virtual DOM; a DOM kept in memory.
4. **Great Developer Tools**. Developer toolset is another important factor when you are choosing a development platform. There are two great tools you should be aware of: React Developer Tools and Redux Developer Tools. Both can be installed as Chrome extensions.

>[More information](https://stories.jotform.com/7-reasons-why-you-should-use-react-ad420c634247)

### Instalation of React JS

For installation intructions go to our React JS Tutorial.

[React GitHub](https://github.com/facebook/react)

* * *

**Comment by steph222** [comment]
> @steph222 this is the information for first 4 tools

Perfect!!

**Comment by steph222** [comment]
## Hasura

### What is Hasura?

Hasura's GraphQL engine is an ultrafast GraphQL server that gives you real-time, snapshot GraphQL APIs over Postgres, with webhook triggers on database events and remote schemas for business logic.


### Why we use Hasura?

1. Helps encapsulate the details of the structure of your tables behind a consistent interface. It also lets you structure your data in an intuitive way.
2. Provides more readability since a named query can set the context much faster than a raw SQL query. You can use a view instead of littering your client code base with complex queries.
3. Views have separate permissions and hence can be used to restrict access to the tables such that users are only allowed to see specific rows and columns.

### Instalation of Hasura
[Hasura CLI instalation](https://hasura.io/docs/1.0/graphql/core/hasura-cli/install-hasura-cli.html).

[Hsura GitHub](https://github.com/hasura)


* * *

## httpie

### What is httpie?
Modern command line HTTP client – user-friendly curl alternative with intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc.

### Why we use httpie?

1. Simple, expressive and intuitive HTTP command syntax.
2. Nicely formatted and colorized terminal output.
3. Out-of-box JSON support.
4. Forms and file uploads.
5. Support for custom HTTP header.
6. Major OS supports — Linux, macOS, and Windows.
7. Supports arbitrary request data.
8. Plugins to support additional feature.

### Instalation of httpie

[httpie instalation](https://httpie.io/docs#installation).

[httpie GitHub](https://github.com/httpie/httpie)

<iframe width="100%" height="315" src="https://www.youtube.com/embed/SUWCS0FCb9s" frameborder="0" allowfullscreen="true"> </iframe>

* * *

## PostgresDB

### What is PostgresDB?

PostgreSQL is a powerful open source object relational database system that uses and extends the SQL language combined with many features that securely store and scale the most complicated data workloads.

### Why we use PostgresDB?

1. Compatible with various platforms using all major languages and middleware
It offers a most sophisticated locking mechanism.
2. Support for multi-version concurrency control.
3. Mature Server-Side Programming Functionality.
4. Compliant with the ANSI SQL standard.
5. Full support for client-server network architecture.

### Instalation of PostgresDB

[PostgresDB instalation](https://www.2ndquadrant.com/en/blog/pginstaller-install-postgresql/)

[PostgresDB GitHub](https://github.com/postgres/postgres)

* * *

## PostMan

### What is PostMan?

It enables developers to test calls to APIs. Postman users enter data. The data is sent to a special web server address. Typically, information is returned, which Postman presents to the user.

### Why we use PostMan?

1. **User-Friendly:** Having a user-friendly interface enables one to send a simple request by only entering it, filling in the necessary headers, selecting the HTTP method and pressing the ‘send’ button. 
2. **Automation:**  Automated tests can be easily set up using the Postman API testing tool. You can automate your test cases in Postman in javascript with impressive features like write test suites, build request that consists of dynamic parameters, pass on data in between the request, etc. In this way tests and requests can be aggregated into a single automated test sequence.
3. **Cost Effective:**  Apart from the many benefits which this tool provides us, this tool is also very cost effective. You can use the Postman in their free plan, which consists of limited features but most helpful.

### Instalation of PostMan

[PostMan Instalation](https://www.softwaretestingmaterial.com/install-postman/)

[PostMan GitHub](https://github.com/postmanlabs)

<iframe width="100%" height="315" src="https://www.youtube.com/embed/juldrxDrSH0" frameborder="0" allowfullscreen="true"> </iframe>

**Comment by Edgar097** [comment]
looks great lets change the title of `instalation of something` to `something instalation`
