### ISSUE TITLE
Compare English and Spanish sites

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#269]
Lets find any missing content that is not available in one of the languages

**Comment by leisterfrancisco** [comment]
## Pautas para desarrolladores / Developer Guidelines
### Pautas para Código Abierto / Open Source Contributing Guidelines
- Periódicamente movemos los nuevos issues a la columna **"Por Hacer"** y manualmente le damos la prioridad apropiada.
- Periodically we move the new Issues to the **To Do** column and manually and give it the appropriate priority.
***
- Usamos el flujo de GitHub https://guides.github.com/introduction/flow/ para solicitar cambios en el código. Desarrollamos en la rama **master** y **release** usando etiquetas y versionamiento.
- We use GitHub flow https://guides.github.com/introduction/flow/ to request code changes. We develop on **master** and **release** using tags with semver versioning.
***
- **_New and reopened pull request are automatically added to the board in the In Progress column_**. Los nuevos y reabiertos **pull request** son autómaticamente añadidos al tablero en la columna **"En Progreso"**.
- New and reopened **pull request** are automatically added to the board in the In **Progress column**.
***
- Pautas para los **pull request**
- **Pull Request** General Guidelines
***
- Por favor revisa para asegurarte que no hay ningún 
pull request existente tratando de localizar o vincular el issue mecionado.
- Please check to make sure that there aren't existing pull requests attempting to address the issue mentioned.

**Comment by leisterfrancisco** [comment]
## Blockchain EOSIO / Learn EOSIO
### Protocolo EOSIO / EOSIO Protocol
- [ ] EOSIO es software de código abierto que permite lanzar redes blockhain altamente configurables sobre las cuales desarrolladores y emprendedores pueden correr aplicaciones blockchain de alto rendimiento. **EOSIO** fue creado en el 2018 y es mantenido por la empresa Block One. La primera red pública lanzada sobre EOSIO se llama EOS, también referida como "mainnet". EOS es una de múltiples redes blockchain públicas actualmente utilizado EOSIO. Puede ver la siguiente lista de redes EOSIO. También existen múltiples redes privadas que actualmente utilizan EOSIO.
- [ ] EOSIO is open-source software that enables launching highly configurable blockchain networks on which developers and entrepreneurs can run highly performant blockchain applications. **EOSIO** was created in 2018 and is maintained by Block One. The first public network launched on EOSIO is called EOS, also referred as "mainnet". EOS is however just one of multiple public blockchain networks currently using EOSIO. Take a look at the following EOSIO network list. There are also multiple private networks currently using EOSIO.
***
- [ ] Finalidad tolerante a fallas bizantinas BFT.
- [ ] *Byzantine Fault Tolerance
***
- [ ] Nombres de cuentas legibles por humanos (**e.g. :** cuentaeosio1).
- [ ] Human Readable Account Names (**e.g. :** eosioaccount )
***
- [ ] **EMPTY**
- [ ] More content
***
- [ ] Otra característica importante de una red blockchain basada en el protocolo EOSIO tiene una arquitectura flexible, en la cual gran parte de las reglas de operación se definen a través de los **contratos del sistema**.
- [ ] Another important feature of EOSIO based blockchain networks is it's flexible architecture, because many of the network's "rules of engagement" are defined through **system contracts**.
***
- [ ] **EMPTY**
- [ ] System contracts
***
### Mecanismo de Consenso / Consensus Mechanism
- [ ] **EMPTY**
- [ ] EOSIO will delegate the the authority to validate and write new blocks to a group of nodes that we call Block Producers.
***
- [ ] ¿Qué es un productor de bloques?
- [ ] What is a block producer
***
- [ ] En redes EOSIO, los productores de bloques activos se enumeran en un cronograma, llamado **schedule**
- [ ] In EOSIO networks, active block producers are listed on a list, called **schedule.**
***
- [ ] La lista de cuentas de productores en el **schedule** se ordena alfabéticamente y así se define la secuencia en que deben firmar bloques.
- [ ] The **schedule** is arranged alphabetically and thus defines the sequence in which block producers must sign blocks.
***
- [ ] **Ejemplo:** Una red de 21 productores activos requiere validación de 15 nodos (2/3 +1), lo cual toma en promedio 90 segundos para obtener irreversibilidad de un bloque nuevo.
- [ ] **Example:** A network of 21 active producers requires validation of 15 nodes (2/3 +1), which takes on average 90 seconds to obtain irreversibility of a new block.
***
- [ ] Una vez que se firma un bloque, otros productores lo validan en el cronograma y pasa a un estado irreversible después de que 2/3 + 1 productores lo hayan validado. Entonces, si 1/3 o más de todos los productores están fuera de línea, el último número de bloque irreversible, conocido como **"Last Irreversible Block"** o **LIB,** no aumentaría y la cadena de bloques se detendrá.
- [ ] Once a block is signed, other producers on the schedule validate it and it goes into an irreversible state after 2/3 + 1 producers have signed. So if 1/3 or more of all producers are offline, the last irreversible block number, known as **Last Irreversible Block** or **LIB,** would not increase and the blockchain will stop.
***
- [ ] Con solo 5 productores, la red tolerará que 1 productor se desconecte. Si más de uno está fuera de línea, el número del **último bloque irreversible (LIB)** dejará de moverse y la red se detendrá. Con 4 nodos, la interrupción de un nodo interrumpirá la operación. Con 9 productores, dos nodos pueden desconectarse sin romper la red.
- [ ] With only 5 producers, the network will tolerate 1 producer going offline. If more than one is offline, the number of the **Last Irreversible Block** will stop increasing and the network will stop. With 4 nodes, a single failed a node will stall the network. With 9 producers, two nodes can be disconnected without breaking the network.
***
### Uso de recursos / System Resources
- [ ] ```
- [ ] `
***
- [ ] Puede encontrar más detalles sobre la CPU como recurso del sistema aquí.
- [ ] You can find more details about the CPU as a resource here
***
- [ ] **EMPTY**
- [ ] The rate at which an uncongested resource expands its limits.
***
- [ ] ```
- [ ] `
***
- [ ] ```
- [ ] `
***
- [ ] ```
- [ ] `
***
- [ ] ```
- [ ] `
***
### Cuentas y Permisos / Accounts And Permissions **(headers hash are incorrect)**
- [ ] Cuentas y Permisos
- [ ] **EMPTY**
***
- [ ] **Por ejemplo**: Cualquier cuenta puede crear un permiso personalizado con su par de llaves únicas para interactuar únicamente con un contrato.
- [ ] **For example**: Any account can create a custom permission with its unique key pair to solely interact with a single contract.
***
- [ ] Consulte la "Guía de inicio rápido" y la guía completa en los documentos del paquete **eos-transit**
- [ ] Please see the "Quick Start" and thorough guide in the **eos-transit package docs**
***
- [ ] En la distribución de EOSIO viene incluido un cliente CLI llamado **cleos** que interactúa con un cliente llamado **keosd** que proporciona un servicio de billetera seguro y un punto final API para aplicaciones que requieren integración de back-end con un proveedor de firmas digitales.
- [ ] In the EOSIO's distribution comes included a CLI client called **cleos** that interacts with lite client called **keosd** which provides a secure wallet service and API endpoint for applications that require back-end integration with a signature provider.
***
### Funciones Importantes en EOSIO / Important Functions in EOSIO
- [ ] Cuenta Privilegiada EOSIO
- [ ] **EMPTY**
***
- [ ] Esta cuenta posee acceso ilimitado a los recursos CPU, NET, y RAM asi como funciones privilegiadas. Esta cuenta privilegiada se denomina **eosio.** 
- [ ] This account has unlimited access to CPU, NET, and RAM resources representing the highest authority of the network which can execute priviledged functions.
***
- [ ] **EMPTY**
- [ ] Usually this authority is invoked by a multi-signature (or "multisig") contract that will require the consent of a super-majorit of the block producers. This privileged account will be called the eosio account.
***
- [ ] Actualiza los limites de recursos asociados a una cuenta Utiliza como parámetros:
- [ ] Update the resource limits associated with an account
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] ```
- [ ] `
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] ```
- [ ] `
***
- [ ] Permite establecer como privilegiada a una cuenta. Parámetros:
- [ ] Allows you to establish an account as privileged. **Parámetros:**
***
- [ ] Utiliza como parámetros:
- [ ] Parameters:
***
- [ ] ```
- [ ] `
***
- [ ]  Utiliza como parámetros:
- [ ] Parameters:
***
- [ ] Utiliza como parámetros:
- [ ] Parameters:
***
- [ ] Utiliza como parámetros:
- [ ] Parameters:
***
- [ ] **e**limina la autorización de permisos de una cuenta . Utiliza como parámetros:
- [ ] **R**emoves permission authorization from an account.
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] Asigna una acción especifica de un contrato a un permiso especifico, cinco acciones no pueden ser linkeadas **updateauth,deleteauth,linkauth,unlikauth,canceldelay**
- [ ] Assign a specific action of a contract to a specific permission, five actions cannot be linked **updateauth,deleteauth,linkauth,unlikauth,canceldelay.**
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] Es la reversa de linkauth Parámetros:
- [ ] It is the reverse of linkauth.
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] Contrato Nativo **eosio.token**
- [ ] Native Token Contract **eosio.token**
***
- [ ] Le permite a una cuenta **issuer** crear un token. Utiliza como parametros:
- [ ] Allows an **issuer** account to create a token.
***
- [ ] **EMPTY**
- [ ] Parameters:
***
- [ ] Utiliza como Parámetros:
- [ ] Parameters:
***
- [ ] . Parámetros:
- [ ] Parameters:
***
- [ ] Parámetros:
- [ ] Parameters:
***
### Manejo de Llaves Privadas / Private Keys
- [ ] **EMPTY**
- [ ] Private Keys Management
***
- [ ] Luego, introducimos las llaves públicas de owner y active para ejecutar el contrato. Estas pueden ser cualquiera de las que se generaron con el comando **cleos create key** anteriormente. Se recomienda no compartir las llaves privadas.
- [ ] Then, we introduce the public keys of owner and active to execute the contract. This should be any of the ones generated with the **cleos create key** command above. Is recommendable not to share the private keys.
***
### Desarrollo de Dapps / Dapp Development
- [ ] Puedes ver más en este canal: https://www.youtube.com/user/apexmaxable/videos
- [ ] More on Max G's channel https://www.youtube.com/user/apexmaxable/videos
***
- [ ] **EOS Local provides a really quick way to setup an EOS local network with IPFS using docker**. EOS Local provee una realmente rápida manera de configuar una red local de EOS con IPFS usando docker.
- [ ] EOS Local provides a really quick way to set up an EOS local network with IPFS using docker.
***
- [ ] Plantilla de EOSIO de Aplicaciones Descentralizadas
- [ ] EOSIO DApp Boilerplate
***
### Contratos Inteligentes / Smart Contracts
- [ ] Un Contrato Inteligente de EOSIO es software registrado en el blockchain y ejecutado en los nodos de EOSIO, esto implementa las semánticas de un contracto cuyo registro de solicitudes de acciones están siendo guardadas en el blockchain. El Contrato Inteligente define la interfaz (acciones, parámetros, estructuras de datos) y el código que implementa la interfaz. El código es compilado en el formato **bytecode canónico** el cual puede ser obtenido y ejecutado por los nodos. El blockchain guarda las transacciones (tranferencias legales, moviemientos de juego) del contrato. Cada Contrato Inteligente debe ser acompañado de un Contrato Ricardiano que define la legalidad de los términos y condiciones enlazadas del contrato.
- [ ] An EOSIO Smart Contract is software registered on the blockchain and executed on EOSIO nodes, that implements the semantics of a "contract" whose ledger of action requests are being stored on the blockchain. The Smart Contract defines the interface (actions, parameters, data structures) and the code that implements the interface. The code is compiled into a **canonical bytecode** format that nodes can retrieve and execute. The blockchain stores the transactions (e.g., legal transfers, game moves) of the contract. Each Smart Contract must be accompanied by a Ricardian Contract that defines the legally binding terms and conditions of the contract.
***
- [ ] Define las acciones o el estado de cambios que deben existir en tu Contrato Inteligente. 
- [ ] Define the actions, or state changes, that must exist in your smart contract 
***
- [ ] También, échale un vistazo a esta lista de Contratos Inteligenes de EOS de código abierto mantenida por César Rodríguez:
- [ ] Also check out this list of open source contracts for EOSIO maintained by César Rodríguez :
***
### ___ / EOSIO Core

**Comment by leisterfrancisco** [comment]
## Blockchain EOSIO / Learn EOSIO
### Protocolo EOSIO / EOSIO Protocol
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***

**Comment by leisterfrancisco** [comment]
##
###
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***
- [ ] 
- [ ] 
***

**Comment by leisterfrancisco** [comment]
## Comunidad / Community **Resources**
### Canales de Telegram / Telegram Channels
- [ ] Los canales de Telegram son una herramienta ideal para difundir mensajes a grandes cantidades de personas. A continuación, se presenta una lista de los canales más relevantes de la comunidad de EOS, en ellos se comparte contenido que puede ser de gran utilidad.
- [ ] Telegram channels are an ideal tool to spread messages to large numbers of people. The following is a list of the most relevant channels of the EOS community, in which content is shared that can be very useful
***
- [ ] Comunidad EOS **Costa Rica**
- [ ] EOS **CR** Community
***
- [ ] EOS Hackathon . (_EXTRA SPACE AND POINT_)
- [ ] EOS Hackathon . (_EXTRA SPACE AND POINT_)
***
### Redes Blockchain basadas en EOSIO / EOSIO based Blockchain Networks
- [ ] Voice : Una cadena de bloques para impulsar la red social descentralizada construida por Block.one
- [ ] Voice: a blockchain to promote a decentralized social network built by Block.one.
***
- [ ] **EMPTY**
- [ ] You can see a complete description of several EOSIO public blockchains here ineos.io
